# Generated by Django 5.2.17 on 2026-08-21 05:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_upcoming', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('category', models.CharField(choices=[('facilities', 'Facilities'), ('students', 'Students'), ('events', 'Events'), ('academics', 'Academics'), ('sports', 'Sports'), ('community', 'Community'), ('general', 'General')], default='general', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLifeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('clubs', 'Clubs'), ('societies', 'Societies'), ('facilities', 'Facilities')], max_length=50, unique=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Custom SVG icon code for this category', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School Life Category',
                'verbose_name_plural': 'School Life Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('deputy_academics', 'Deputy Principal (Academics)'), ('deputy_admin', 'Deputy Principal (Administration)'), ('head_academics', 'Head of Academics'), ('dean_students', 'Dean of Students'), ('head_finance', 'Head of Finance'), ('hod', 'Head of Department'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('support', 'Support Staff')], default='teacher', max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.TextField(blank=True, help_text='List qualifications, one per line', null=True)),
                ('order', models.IntegerField(default=0, help_text='Lower number = higher display priority')),
                ('is_active', models.BooleanField(default=True)),
                ('is_leadership', models.BooleanField(default=False, help_text='Show on leadership page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='academicprogram',
            name='icon',
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Custom SVG icon code', null=True),
        ),
        migrations.CreateModel(
            name='SchoolLifeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='school_life/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('icon_svg', models.TextField(blank=True, help_text='Custom SVG icon for this item', null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='schools.schoollifecategory')),
            ],
            options={
                'verbose_name': 'School Life Item',
                'verbose_name_plural': 'School Life Items',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
