# Generated by Django 5.2.17 on 2026-09-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0002_event_gallery_schoollifecategory_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone (Students, Parents, Staff)'), ('students', 'All Students'), ('parents', 'All Parents'), ('teachers', 'All Teachers'), ('specific_class', 'Specific Class')], default='all', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Announcement auto-hides after this date.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_class', models.ForeignKey(blank=True, help_text="Only used when audience is 'Specific Class'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='classes.class')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-published_at'],
            },
        ),
    ]
