# Generated by Django 5.2.17 on 2026-09-14 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0003_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Human-readable staff ID, e.g. STAFF-2026-001', max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_hired', models.DateField()),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('intern', 'Intern'), ('part_time', 'Part-Time'), ('volunteer', 'Volunteer')], default='permanent', max_length=20)),
                ('contract_end_date', models.DateField(blank=True, help_text='Required for contract staff.', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('must_change_password', models.BooleanField(default=True, help_text='Forces password change on next login (for admin-created accounts).')),
                ('mfa_required', models.BooleanField(default=False, help_text='Set True for high-privilege roles (admin, principal, bursar, HOD).')),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Set True once the staff has completed MFA setup.')),
                ('mfa_secret', models.CharField(blank=True, help_text='TOTP secret (stored encrypted at rest).', max_length=255, null=True)),
                ('mfa_backup_codes', models.JSONField(blank=True, default=list, help_text='Hashed backup codes for MFA recovery.')),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True, null=True)),
                ('access_review_date', models.DateField(blank=True, help_text='Next scheduled access review.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.OneToOneField(blank=True, help_text='Optional link to public-facing bio on the school website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_profile', to='schools.staff')),
                ('deactivated_by', models.ForeignKey(blank=True, help_text="Who revoked this staff's access.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user used for login (email + password).', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=10, help_text='Lower number = higher authority. 1 = Admin, 10 = lowest.')),
                ('requires_mfa', models.BooleanField(default=False, help_text='Whether staff with this role must use MFA.')),
                ('dashboard_config', models.JSONField(blank=True, default=dict, help_text='Defines sidebar items and quick actions. Example: {"sidebar": ["dashboard", "grade-entry"], "quick_actions": ["enter_grades"]}')),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted by admin.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_permissions', models.ManyToManyField(blank=True, help_text='Django permissions granted by default.', related_name='staff_roles', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Staff Role',
                'verbose_name_plural': 'Staff Roles',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. For temporary role elevation.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='staff.staffrole')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Role Assignment',
                'verbose_name_plural': 'Staff Role Assignments',
                'ordering': ['staff', 'role__level'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_staff_id', models.CharField(blank=True, help_text='Cached staff_id — survives actor deletion.', max_length=50, null=True)),
                ('actor_name', models.CharField(blank=True, help_text='Cached full name — survives actor deletion.', max_length=200, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('permission_change', 'Permission Change'), ('role_assign', 'Role Assignment'), ('role_revoke', 'Role Revocation'), ('force_logout', 'Force Logout'), ('export', 'Data Export'), ('grade_publish', 'Grade Publish'), ('fee_waiver', 'Fee Waiver'), ('approval_granted', 'Approval Granted'), ('approval_rejected', 'Approval Rejected'), ('other', 'Other')], max_length=30)),
                ('model_name', models.CharField(blank=True, help_text="Affected model, e.g. 'Grade' or 'Student'.", max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_repr', models.TextField(blank=True, help_text='Human-readable representation of the object.', null=True)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Diff of what changed: {'field': {'before': x, 'after': y}}.")),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action. Null if system action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='staff_audit_actor_i_1f5419_idx'), models.Index(fields=['model_name', 'object_id'], name='staff_audit_model_n_32a93a_idx'), models.Index(fields=['action', '-timestamp'], name='staff_audit_action_cf7829_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('grade_change', 'Grade Change (after publish)'), ('fee_waiver', 'Fee Waiver'), ('bulk_export', 'Bulk Data Export'), ('permission_elevation', 'Permission Elevation'), ('student_delete', 'Student Deletion'), ('staff_delete', 'Staff Deletion'), ('other', 'Other')], max_length=30)),
                ('target_model', models.CharField(help_text="Model name, e.g. 'Grade'.", max_length=100)),
                ('target_object_id', models.CharField(max_length=100)),
                ('current_value', models.JSONField(default=dict, help_text='Snapshot of current state.')),
                ('requested_value', models.JSONField(default=dict, help_text='Proposed new state.')),
                ('reason', models.TextField(help_text='Why is this change needed? (Required for audit trail.)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When the approved change was applied.', null=True)),
                ('expires_at', models.DateTimeField(help_text='Auto-expires if not reviewed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='staff_chang_status_aaeb43_idx'), models.Index(fields=['requested_by', '-created_at'], name='staff_chang_request_b4e4da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='staff_staff_staff_i_1228db_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='staff_staff_is_acti_0db61a_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffroleassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('staff', 'role'), name='unique_active_staff_role'),
        ),
    ]
