# Generated by Django 5.2.17 on 2026-09-13 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_announcement'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=50)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('step_parent', 'Step-Parent'), ('grandparent', 'Grandparent'), ('other', 'Other')], default='guardian', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=False, help_text="Set True when admin resets the parent's password.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('step_parent', 'Step-Parent'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(help_text='Primary phone for this guardian', max_length=20)),
                ('national_id', models.CharField(help_text='National ID / Passport number', max_length=50)),
                ('email', models.EmailField(help_text='Used for sending invitations', max_length=254)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this student')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Guardian',
                'verbose_name_plural': 'Student Guardians',
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email the invitation is sent to', max_length=254)),
                ('invite_type', models.CharField(choices=[('initial', 'Initial Invitation'), ('coparent', 'Co-Parent Invitation'), ('resend', 'Resent Invitation')], default='initial', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Failed accept attempts')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by_parent', models.ForeignKey(blank=True, help_text='If a parent invited a co-parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='parents.parent')),
                ('invited_by_staff', models.ForeignKey(blank=True, help_text='If admin/staff sent the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_invitations_sent', to='schools.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_invitations', to='students.student')),
                ('student_guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='parents.studentguardian')),
            ],
            options={
                'verbose_name': 'Parent Invitation',
                'verbose_name_plural': 'Parent Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal Guardian'), ('step_parent', 'Step-Parent'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=20)),
                ('can_view_academic', models.BooleanField(default=True, help_text='Can view grades, attendance, timetable, assignments, etc.')),
                ('can_view_financials', models.BooleanField(default=True, help_text='Can view fees, payments, balances.')),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Only one primary contact per student. Used for urgent communications.')),
                ('linked_via', models.CharField(choices=[('invitation', 'Via Invitation'), ('self_service', 'Self-Service Link'), ('coparent_invite', 'Invited by Co-Parent'), ('admin', 'Created by Admin')], default='invitation', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='parents.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'verbose_name': 'Student-Parent Link',
                'verbose_name_plural': 'Student-Parent Links',
                'ordering': ['-is_primary_contact', 'student', 'parent'],
            },
        ),
        migrations.CreateModel(
            name='ParentLinkAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_attempted', models.CharField(blank=True, max_length=20, null=True)),
                ('national_id_attempted', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, choices=[('invalid_token', 'Invalid Token'), ('expired', 'Token Expired'), ('revoked', 'Token Revoked'), ('already_accepted', 'Token Already Accepted'), ('phone_mismatch', 'Phone Mismatch'), ('id_mismatch', 'National ID Mismatch'), ('dob_mismatch', 'Student DOB Mismatch'), ('already_linked', 'Student Already Linked to This Parent'), ('too_many_attempts', 'Too Many Attempts'), ('rate_limited', 'Rate Limited'), ('email_conflict', 'Email Already in Use'), ('other', 'Other')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_attempts', to='parents.parentinvitation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_attempts', to='parents.parent')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_link_attempts', to='students.student')),
            ],
            options={
                'verbose_name': 'Parent Link Attempt',
                'verbose_name_plural': 'Parent Link Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='parents_par_ip_addr_1b075a_idx'), models.Index(fields=['student', 'created_at'], name='parents_par_student_d9117e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'phone'), name='unique_guardian_phone_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'national_id'), name='unique_guardian_national_id_per_student'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='only_one_primary_guardian_per_student'),
        ),
        migrations.AddIndex(
            model_name='parentinvitation',
            index=models.Index(fields=['token', 'expires_at'], name='parents_par_token_18f9f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='unique_parent_student_link'),
        ),
        migrations.AddConstraint(
            model_name='studentparent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary_contact', True)), fields=('student',), name='only_one_primary_contact_per_student'),
        ),
    ]
